const data = [[
    { value: 1, hide: 0 },
    { value: 7, hide: 0 },
    { value: 2, hide: 1 },
    { value: 4, hide: 0 },
    { value: 5, hide: 0 },
    { value: 8, hide: 0 },
    { value: 3, hide: 0 },
    { value: 6, hide: 0 },
    { value: 9, hide: 1 },
], [
    { value: 8, hide: 0 },
    { value: 5, hide: 0 },
    { value: 4, hide: 0 },
    { value: 6, hide: 0 },
    { value: 3, hide: 0 },
    { value: 9, hide: 1 },
    { value: 1, hide: 0 },
    { value: 2, hide: 0 },
    { value: 7, hide: 1 },
], [
    { value: 3, hide: 0 },
    { value: 6, hide: 1 },
    { value: 9, hide: 0 },
    { value: 7, hide: 0 },
    { value: 1, hide: 1 },
    { value: 2, hide: 0 },
    { value: 4, hide: 0 },
    { value: 5, hide: 1 },
    { value: 8, hide: 0 },
], [
    { value: 4, hide: 0 },
    { value: 1, hide: 0 },
    { value: 7, hide: 0 },
    { value: 5, hide: 1 },
    { value: 9, hide: 0 },
    { value: 6, hide: 0 },
    { value: 8, hide: 1 },
    { value: 3, hide: 1 },
    { value: 2, hide: 1 },
], [
    { value: 6, hide: 0 },
    { value: 2, hide: 0 },
    { value: 3, hide: 0 },
    { value: 8, hide: 0 },
    { value: 7, hide: 1 },
    { value: 1, hide: 0 },
    { value: 9, hide: 1 },
    { value: 4, hide: 1 },
    { value: 5, hide: 0 },
], [
    { value: 9, hide: 1 },
    { value: 8, hide: 1 },
    { value: 5, hide: 1 },
    { value: 3, hide: 1 },
    { value: 2, hide: 1 },
    { value: 4, hide: 1 },
    { value: 7, hide: 0 },
    { value: 1, hide: 1 },
    { value: 6, hide: 1 },
], [
    { value: 5, hide: 0 },
    { value: 3, hide: 0 },
    { value: 6, hide: 1 },
    { value: 9, hide: 0 },
    { value: 4, hide: 0 },
    { value: 7, hide: 0 },
    { value: 2, hide: 0 },
    { value: 8, hide: 0 },
    { value: 1, hide: 1 },
], [
    { value: 7, hide: 1 },
    { value: 4, hide: 1 },
    { value: 1, hide: 1 },
    { value: 2, hide: 0 },
    { value: 8, hide: 1 },
    { value: 5, hide: 1 },
    { value: 6, hide: 1 },
    { value: 9, hide: 0 },
    { value: 3, hide: 0 },
], [
    { value: 2, hide: 1 },
    { value: 9, hide: 1 },
    { value: 8, hide: 0 },
    { value: 1, hide: 0 },
    { value: 6, hide: 0 },
    { value: 3, hide: 1 },
    { value: 5, hide: 1 },
    { value: 7, hide: 1 },
    { value: 4, hide: 1 },
]];

export default data;